server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names: master
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/laravel?characterEncoding=utf-8
        username: sail
        password: password
    sharding:
      tables:
        tab_user:
          actual-data-nodes: master.tab_user$->{0..2}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: tab_user$->{id % 3}
    props:
      sql:
        show=true:
