server:
  port: 8080

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-active: 20
      initial-size: 1
      min-idle: 1
      filters: stat,wall
      stat-view-servlet:
        enabled: true # sql监控页面 http://localhost:8080/druid/index.html
        allow:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names: master
      master:
        type: hi.config.MyDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/laravel?characterEncoding=utf-8
        username: sail
        password: password
    sharding:
      tables:
        tab_user:
          actual-data-nodes: master.tab_user$->{0..2}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: tab_user$->{id % 3}
    props:
      sql:
        show: true
