server:
  port: 8080

spring:
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        allow:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names: master
      master:
        type: hi.config.MyDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/laravel?characterEncoding=utf-8
        username: sail
        password: password
    sharding:
      tables:
        user:
          interval: 86400
          actual-data-nodes: master.not_exits
          key-generator:
            column: id
            type: SNOWFLAKE
          table-strategy:
            standard:
              sharding-column: created_at
              precise-algorithm-class-name: hi.sharding.algorithm.DateShardingAlgorithm
              range-algorithm-class-name: hi.sharding.algorithm.DateShardingAlgorithm
    props:
      sql:
        show: true
