server:
  port: 8080

spring:
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        allow:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    props:
      sql-show: true
    datasource:
      names: master
      master:
        type: hi.config.MyDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/laravel?characterEncoding=utf-8
        username: sail
        password: password
    rules:
      sharding:
        sharding-algorithms:
          my-algorithms:
            type: CLASS_BASED
            props:
              strategy: standard
              algorithmClassName: hi.sharding.algorithm.DateShardingAlgorithm
        tables:
          user:
            interval: 86400
            actual-data-nodes: master.user$->{0..100000}
            key-generate-strategy:
              column: id
              key-generator-name: SNOWFLAKE
            table-strategy:
              standard:
                sharding-column: created_at
                sharding-algorithm-name: my-algorithms
